CREATE TABLE WORKERS(
    ID NUMBER NOT NULL ,
    PRIMARY KEY(ID),
    NAME VARCHAR2(100) NOT NULL ,
    CONSTRAINT UNQ_WORKERS UNIQUE(NAME),
    CREATED_AT DATE NOT NULL DEFAULT (SYSDATE ),
    CREATED_AT_STR VARCHAR2(75) NULL AS(TO_CHAR("CREATED_AT",'yyyy-mm-dd hh24:mi:ss'))
);

CREATE INDEX IDX_WORKERS ON WORKERS(CREATED_AT);